baseURL = "https://portfolio.k-work.space/"
title = "K's Workspace"
languageCode = "ja"
defaultContentLanguage = "ja"
theme = "book"

# 階層の並び替え・目次の生成など（必要に応じて）
[markup]
  [markup.tableOfContents]
    startLevel = 2
    endLevel = 4

[params]
  BookSection = 'docs'
  BookToC = true          # 右側の目次
  BookSectionPagesMenu = "main"  # セクション自動メニュー
  BookSearch = true
  BookRepo = ""           # GitHub リポジトリURLを載せたい場合
  BookDateFormat = "2006-01-02"
  BookComments = false
  BookTheme = 'auto'

[services]
  [services.googleAnalytics]
    id = 'G-PH7P4FG1P9'

[menu]
[[menu.home]]
  name = 'About'
  pageRef = '/docs/about'
  weight = 1

[[menu.home]]
  name = 'Knowledge'
  pageRef = '/docs/knowledge'
  weight = 2

[[menu.home]]
  name = 'Lightdash'
  pageRef = '/docs/knowledge/lightdash/'
  weight = 1
  parent = 'Knowledge'

[[menu.home]]
  name = 'Dialy'
  pageRef = '/docs'
  weight = 3

[[menu.home]]
  name = '2025'
  pageRef = '/docs/dialy'
  weight = 1
  parent = 'Dialy'